[package]
name = "chuck"
version = "0.1.0"
authors = ["Nino Paparo"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.8", features = ["json"] }
tokio = { version = "1.15.0", features = ["full"] }
serde = { version = "1.0.133", features = ["derive"] }
wiremock = "0.5.8"
json = "0.12.4"
serde_json = "1.0.74"
dialoguer = "0.9.0"
color-eyre = "0.5.11"
