name: Semver checks

on:
  push:
    branches:
      - master
      
jobs:
  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check semver for my-crate
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
         manifest-path: ./Cargo.toml  # or just semver/my-crate/
